from dataclasses import dataclass

from utils.column_names.ind_cqc_pipeline_columns import (
    IndCqcColumns,
)
from utils.column_values.categorical_column_values import MainJobRoleLabels

from utils.validation.validation_rule_names import RuleNames as RuleName


@dataclass
class EstimatedIndCqcFilledPostsByJobRoleValidationRules:
    rules_to_check = {
        RuleName.size_of_dataset: None,
        RuleName.complete_columns: [
            IndCqcColumns.location_id,
            IndCqcColumns.ascwds_workplace_import_date,
            IndCqcColumns.cqc_location_import_date,
            IndCqcColumns.care_home,
            IndCqcColumns.primary_service_type,
            IndCqcColumns.current_ons_import_date,
            IndCqcColumns.current_cssr,
            IndCqcColumns.current_region,
            IndCqcColumns.unix_time,
            IndCqcColumns.estimate_filled_posts,
            IndCqcColumns.estimate_filled_posts_source,
            IndCqcColumns.ascwds_job_role_ratios_merged,
            IndCqcColumns.ascwds_job_role_ratios_merged_source,
            IndCqcColumns.estimate_filled_posts_by_job_role,
            MainJobRoleLabels.activites_worker,
            MainJobRoleLabels.admin_staff,
            MainJobRoleLabels.advocacy,
            MainJobRoleLabels.allied_health_professional,
            MainJobRoleLabels.ancillary_staff,
            MainJobRoleLabels.assessment_officer,
            MainJobRoleLabels.care_coordinator,
            MainJobRoleLabels.care_worker,
            MainJobRoleLabels.childrens_roles,
            MainJobRoleLabels.community_support_and_outreach,
            MainJobRoleLabels.data_analyst,
            MainJobRoleLabels.data_governance_manager,
            MainJobRoleLabels.deputy_manager,
            MainJobRoleLabels.employment_support,
            MainJobRoleLabels.first_line_manager,
            MainJobRoleLabels.it_and_digital_support,
            MainJobRoleLabels.it_manager,
            MainJobRoleLabels.it_service_desk_manager,
            MainJobRoleLabels.learning_and_development_lead,
            MainJobRoleLabels.middle_management,
            MainJobRoleLabels.nursing_assistant,
            MainJobRoleLabels.occupational_therapist,
            MainJobRoleLabels.occupational_therapist_assistant,
            MainJobRoleLabels.other_care_role,
            MainJobRoleLabels.other_managerial_staff,
            MainJobRoleLabels.other_non_care_related_staff,
            MainJobRoleLabels.registered_manager,
            MainJobRoleLabels.registered_nurse,
            MainJobRoleLabels.registered_nursing_associate,
            MainJobRoleLabels.safeguarding_officer,
            MainJobRoleLabels.senior_care_worker,
            MainJobRoleLabels.senior_management,
            MainJobRoleLabels.social_worker,
            MainJobRoleLabels.software_developer,
            MainJobRoleLabels.supervisor,
            MainJobRoleLabels.support_worker,
            MainJobRoleLabels.team_leader,
            MainJobRoleLabels.technician,
        ],
        RuleName.index_columns: [
            IndCqcColumns.location_id,
            IndCqcColumns.cqc_location_import_date,
        ],
        RuleName.min_values: {
            MainJobRoleLabels.activites_worker: 0.0,
            MainJobRoleLabels.admin_staff: 0.0,
            MainJobRoleLabels.advocacy: 0.0,
            MainJobRoleLabels.allied_health_professional: 0.0,
            MainJobRoleLabels.ancillary_staff: 0.0,
            MainJobRoleLabels.assessment_officer: 0.0,
            MainJobRoleLabels.care_coordinator: 0.0,
            MainJobRoleLabels.care_worker: 0.0,
            MainJobRoleLabels.childrens_roles: 0.0,
            MainJobRoleLabels.community_support_and_outreach: 0.0,
            MainJobRoleLabels.data_analyst: 0.0,
            MainJobRoleLabels.data_governance_manager: 0.0,
            MainJobRoleLabels.deputy_manager: 0.0,
            MainJobRoleLabels.employment_support: 0.0,
            MainJobRoleLabels.first_line_manager: 0.0,
            MainJobRoleLabels.it_and_digital_support: 0.0,
            MainJobRoleLabels.it_manager: 0.0,
            MainJobRoleLabels.it_service_desk_manager: 0.0,
            MainJobRoleLabels.learning_and_development_lead: 0.0,
            MainJobRoleLabels.middle_management: 0.0,
            MainJobRoleLabels.nursing_assistant: 0.0,
            MainJobRoleLabels.occupational_therapist: 0.0,
            MainJobRoleLabels.occupational_therapist_assistant: 0.0,
            MainJobRoleLabels.other_care_role: 0.0,
            MainJobRoleLabels.other_managerial_staff: 0.0,
            MainJobRoleLabels.other_non_care_related_staff: 0.0,
            MainJobRoleLabels.registered_manager: 0.0,
            MainJobRoleLabels.registered_nurse: 0.0,
            MainJobRoleLabels.registered_nursing_associate: 0.0,
            MainJobRoleLabels.safeguarding_officer: 0.0,
            MainJobRoleLabels.senior_care_worker: 0.0,
            MainJobRoleLabels.senior_management: 0.0,
            MainJobRoleLabels.social_worker: 0.0,
            MainJobRoleLabels.software_developer: 0.0,
            MainJobRoleLabels.supervisor: 0.0,
            MainJobRoleLabels.support_worker: 0.0,
            MainJobRoleLabels.team_leader: 0.0,
            MainJobRoleLabels.technician: 0.0,
        },
    }
