from dataclasses import dataclass

from utils.column_names.ind_cqc_pipeline_columns import (
    IndCqcColumns,
)
from utils.column_names.cleaned_data_files.cqc_location_cleaned_values import (
    CqcLocationCleanedValues as CQCLValues,
)
from utils.column_names.cleaned_data_files.cqc_pir_cleaned_values import (
    CqcPIRCleanedValues as PIRValues,
)
from utils.validation.validation_rule_names import RuleNames as RuleName


@dataclass
class MergedIndCqcValidationRules:
    rules_to_check = {
        RuleName.size_of_dataset: None,
        RuleName.complete_columns: [
            IndCqcColumns.location_id,
            IndCqcColumns.ascwds_workplace_import_date,
            IndCqcColumns.cqc_location_import_date,
            IndCqcColumns.cqc_pir_import_date,
            IndCqcColumns.care_home,
            IndCqcColumns.provider_id,
            IndCqcColumns.cqc_sector,
            IndCqcColumns.registration_status,
            IndCqcColumns.registration_date,
            IndCqcColumns.dormancy,
            IndCqcColumns.number_of_beds,
            IndCqcColumns.primary_service_type,
            IndCqcColumns.contemporary_ons_import_date,
            IndCqcColumns.contemporary_cssr,
            IndCqcColumns.contemporary_region,
            IndCqcColumns.current_ons_import_date,
            IndCqcColumns.current_cssr,
            IndCqcColumns.current_region,
            IndCqcColumns.current_rural_urban_indicator_2011,
            IndCqcColumns.people_directly_employed,
            IndCqcColumns.establishment_id,
            IndCqcColumns.organisation_id,
        ],
        RuleName.index_columns: [
            IndCqcColumns.location_id,
            IndCqcColumns.cqc_location_import_date,
        ],
        RuleName.categorical_values_in_columns: {
            IndCqcColumns.care_home: [PIRValues.yes, PIRValues.no],
            IndCqcColumns.cqc_sector: [CQCLValues.independent],
            IndCqcColumns.registration_status: [CQCLValues.registered],
            IndCqcColumns.dormancy: ["Y", "N"],
            IndCqcColumns.primary_service_type: [
                CQCLValues.care_home_only,
                CQCLValues.care_home_with_nursing,
                CQCLValues.non_residential,
            ],
            IndCqcColumns.contemporary_cssr: [
                "Barking & Dagenham",
                "Barnet",
                "Barnsley",
                "Bath and North East Somerset",
                "Bedford",
                "Bexley",
                "Birmingham",
                "Blackburn with Darwen",
                "Blackpool",
                "Bolton",
                "Bournemouth",
                "Bournemouth Christchurch and Poole",
                "Bracknell Forest",
                "Bradford",
                "Brent",
                "Brighton & Hove",
                "Bristol",
                "Bromley",
                "Buckinghamshire",
                "Bury",
                "Calderdale",
                "Cambridgeshire",
                "Camden",
                "Central Bedfordshire",
                "Cheshire East",
                "Cheshire West & Chester",
                "City of London",
                "Cornwall",
                "Coventry",
                "Croydon",
                "Cumberland",
                "Cumbria",
                "Darlington",
                "Derby",
                "Derbyshire",
                "Devon",
                "Doncaster",
                "Dorset",
                "Dudley",
                "Durham",
                "Ealing",
                "East Riding of Yorkshire",
                "East Sussex",
                "Enfield",
                "Essex",
                "Gateshead",
                "Gloucestershire",
                "Greenwich",
                "Hackney",
                "Halton",
                "Hammersmith & Fulham",
                "Hampshire",
                "Haringey",
                "Harrow",
                "Hartlepool",
                "Havering",
                "Herefordshire",
                "Hertfordshire",
                "Hillingdon",
                "Hounslow",
                "Isle of Wight",
                "Isles of Scilly",
                "Islington",
                "Kensington & Chelsea",
                "Kent",
                "Kingston upon Hull",
                "Kingston upon Thames",
                "Kirklees",
                "Knowsley",
                "Lambeth",
                "Lancashire",
                "Leeds",
                "Leicester",
                "Leicestershire",
                "Lewisham",
                "Lincolnshire",
                "Liverpool",
                "Luton",
                "Manchester",
                "Medway",
                "Merton",
                "Middlesbrough",
                "Milton Keynes",
                "Newcastle upon Tyne",
                "Newham",
                "Norfolk",
                "North East Lincolnshire",
                "North Lincolnshire",
                "North Northamptonshire",
                "North Somerset",
                "North Tyneside",
                "North Yorkshire",
                "Northamptonshire",
                "Northumberland",
                "Nottingham",
                "Nottinghamshire",
                "Oldham",
                "Oxfordshire",
                "Peterborough",
                "Plymouth",
                "Poole",
                "Portsmouth",
                "Reading",
                "Redbridge",
                "Redcar & Cleveland",
                "Richmond upon Thames",
                "Rochdale",
                "Rotherham",
                "Rutland",
                "Salford",
                "Sandwell",
                "Sefton",
                "Sheffield",
                "Shropshire",
                "Slough",
                "Solihull",
                "Somerset",
                "South Gloucestershire",
                "South Tyneside",
                "Southampton",
                "Southend on Sea",
                "Southwark",
                "St Helens",
                "Staffordshire",
                "Stockport",
                "Stockton on Tees",
                "Stoke on Trent",
                "Suffolk",
                "Sunderland",
                "Surrey",
                "Sutton",
                "Swindon",
                "Tameside",
                "Telford & Wrekin",
                "Thurrock",
                "Torbay",
                "Tower Hamlets",
                "Trafford",
                "Wakefield",
                "Walsall",
                "Waltham Forest",
                "Wandsworth",
                "Warrington",
                "Warwickshire",
                "West Berkshire",
                "West Northamptonshire",
                "West Sussex",
                "Westminster",
                "Westmorland and Furness",
                "Wigan",
                "Wiltshire",
                "Windsor & Maidenhead",
                "Wirral",
                "Wokingham",
                "Wolverhampton",
                "Worcestershire",
                "York",
            ],
            IndCqcColumns.contemporary_region: [
                "East Midlands",
                "Eastern",
                "London",
                "North East",
                "North West",
                "South East",
                "South West",
                "West Midlands",
                "Yorkshire and the Humber",
            ],
            IndCqcColumns.current_cssr: [
                "Barking & Dagenham",
                "Barnet",
                "Barnsley",
                "Bath and North East Somerset",
                "Bedford",
                "Bexley",
                "Birmingham",
                "Blackburn with Darwen",
                "Blackpool",
                "Bolton",
                "Bournemouth",
                "Bournemouth Christchurch and Poole",
                "Bracknell Forest",
                "Bradford",
                "Brent",
                "Brighton & Hove",
                "Bristol",
                "Bromley",
                "Buckinghamshire",
                "Bury",
                "Calderdale",
                "Cambridgeshire",
                "Camden",
                "Central Bedfordshire",
                "Cheshire East",
                "Cheshire West & Chester",
                "City of London",
                "Cornwall",
                "Coventry",
                "Croydon",
                "Cumberland",
                "Cumbria",
                "Darlington",
                "Derby",
                "Derbyshire",
                "Devon",
                "Doncaster",
                "Dorset",
                "Dudley",
                "Durham",
                "Ealing",
                "East Riding of Yorkshire",
                "East Sussex",
                "Enfield",
                "Essex",
                "Gateshead",
                "Gloucestershire",
                "Greenwich",
                "Hackney",
                "Halton",
                "Hammersmith & Fulham",
                "Hampshire",
                "Haringey",
                "Harrow",
                "Hartlepool",
                "Havering",
                "Herefordshire",
                "Hertfordshire",
                "Hillingdon",
                "Hounslow",
                "Isle of Wight",
                "Isles of Scilly",
                "Islington",
                "Kensington & Chelsea",
                "Kent",
                "Kingston upon Hull",
                "Kingston upon Thames",
                "Kirklees",
                "Knowsley",
                "Lambeth",
                "Lancashire",
                "Leeds",
                "Leicester",
                "Leicestershire",
                "Lewisham",
                "Lincolnshire",
                "Liverpool",
                "Luton",
                "Manchester",
                "Medway",
                "Merton",
                "Middlesbrough",
                "Milton Keynes",
                "Newcastle upon Tyne",
                "Newham",
                "Norfolk",
                "North East Lincolnshire",
                "North Lincolnshire",
                "North Northamptonshire",
                "North Somerset",
                "North Tyneside",
                "North Yorkshire",
                "Northamptonshire",
                "Northumberland",
                "Nottingham",
                "Nottinghamshire",
                "Oldham",
                "Oxfordshire",
                "Peterborough",
                "Plymouth",
                "Poole",
                "Portsmouth",
                "Reading",
                "Redbridge",
                "Redcar & Cleveland",
                "Richmond upon Thames",
                "Rochdale",
                "Rotherham",
                "Rutland",
                "Salford",
                "Sandwell",
                "Sefton",
                "Sheffield",
                "Shropshire",
                "Slough",
                "Solihull",
                "Somerset",
                "South Gloucestershire",
                "South Tyneside",
                "Southampton",
                "Southend on Sea",
                "Southwark",
                "St Helens",
                "Staffordshire",
                "Stockport",
                "Stockton on Tees",
                "Stoke on Trent",
                "Suffolk",
                "Sunderland",
                "Surrey",
                "Sutton",
                "Swindon",
                "Tameside",
                "Telford & Wrekin",
                "Thurrock",
                "Torbay",
                "Tower Hamlets",
                "Trafford",
                "Wakefield",
                "Walsall",
                "Waltham Forest",
                "Wandsworth",
                "Warrington",
                "Warwickshire",
                "West Berkshire",
                "West Northamptonshire",
                "West Sussex",
                "Westminster",
                "Westmorland and Furness",
                "Wigan",
                "Wiltshire",
                "Windsor & Maidenhead",
                "Wirral",
                "Wokingham",
                "Wolverhampton",
                "Worcestershire",
                "York",
            ],
            IndCqcColumns.current_region: [
                "East Midlands",
                "Eastern",
                "London",
                "North East",
                "North West",
                "South East",
                "South West",
                "West Midlands",
                "Yorkshire and the Humber",
            ],
            IndCqcColumns.current_rural_urban_indicator_2011: [
                "Rural hamlet and isolated dwellings in a sparse setting",
                "Rural hamlet and isolated dwellings",
                "Rural village",
                "Rural town and fringe in a sparse setting",
                "Rural town and fringe",
                "Urban city and town in a sparse setting",
                "Urban city and town",
                "Urban major conurbation",
                "Urban minor conurbation",
                "Rural village in a sparse setting",
            ],
        },
    }
