from projects._03_independent_cqc._05_model.utils.model import ModelType
import os

ENVIRONMENT = os.environ.get("ENVIRONMENT")

model_definitions = {
    "non_res_pir": {
        "preprocessor": "preprocess_non_res_pir",
        "preprocessor_kwargs": {},
        "model_type": ModelType.SIMPLE_LINEAR.value,
        "model_identifier": "non_res_pir",
        "model_params": dict(),
        "version_parameter_location": f"/models/{ENVIRONMENT}/non_res_pir",
        "source_prefix": "domain=ind_cqc_filled_posts/dataset=ind_cqc_estimated_missing_ascwds_filled_posts",
        "processed_location": "domain=ind_cqc_filled_posts/dataset=ind_cqc_estimated_missing_ascwds_filled_posts_processed",
        "target_columns": ["ascwds_filled_posts_deduplicated_clean"],
        "feature_columns": ["pir_people_directly_employed_deduplicated"],
    },
    "care_home_filled_posts_prediction": {
        "preprocessor": "preprocess_remove_nulls",
        "preprocessor_kwargs": {
            "columns": [
                "activity_count_capped",
                "cqc_location_import_date_indexed",
                "numberOfBeds",
                "banded_bed_ratio_rolling_average_model",
                "service_count_capped",
                "service_care_home_with_nursing",
                "service_care_home_without_nursing",
                "service_domiciliary",
                "service_extra_care_housing",
                "service_shared_lives",
                "service_specialist_college",
                "service_supported_living",
                "specialism_adults_over_65",
                "specialism_adults_under_65",
                "specialism_children",
                "specialism_dementia",
                "specialism_learning_disabilities",
                "specialism_mental_health",
                "specialism_physical_disabilities",
                "specialism_whole_population",
                "rui_rural_hamlet",
                "rui_rural_hamlet_sparse",
                "rui_rural_town",
                "rui_rural_town_sparse",
                "rui_rural_village",
                "rui_urban_city",
                "rui_urban_city_sparse",
                "rui_urban_major",
                "rui_urban_minor",
                "region_east_midlands",
                "region_eastern",
                "region_london",
                "region_north_east",
                "region_north_west",
                "region_south_east",
                "region_south_west",
                "region_west_midlands",
                "region_yorkshire_and_the_humber",
                "imputed_filled_posts_per_bed_ratio_model",
            ],
        },
        "model_type": ModelType.LASSO.value,
        "model_identifier": "care_home_filled_posts_prediction",
        "model_params": {"alpha": 0.001},
        "version_parameter_location": f"/models/{ENVIRONMENT}/care_home_filled_posts_prediction",
        "source_prefix": "domain=ind_cqc_filled_posts/dataset=ind_cqc_features_care_home",
        "processed_location": "domain=ind_cqc_filled_posts/dataset=ind_cqc_features_care_home_processed",
        "target_columns": ["imputed_filled_posts_per_bed_ratio_model"],
        "feature_columns": [
            "activity_count_capped",
            "cqc_location_import_date_indexed",
            "numberOfBeds",
            "banded_bed_ratio_rolling_average_model",
            "service_count_capped",
            "service_care_home_with_nursing",
            "service_care_home_without_nursing",
            "service_domiciliary",
            "service_extra_care_housing",
            "service_shared_lives",
            "service_specialist_college",
            "service_supported_living",
            "specialism_adults_over_65",
            "specialism_adults_under_65",
            "specialism_children",
            "specialism_dementia",
            "specialism_learning_disabilities",
            "specialism_mental_health",
            "specialism_physical_disabilities",
            "specialism_whole_population",
            "rui_rural_hamlet",
            "rui_rural_hamlet_sparse",
            "rui_rural_town",
            "rui_rural_town_sparse",
            "rui_rural_village",
            "rui_urban_city",
            "rui_urban_city_sparse",
            "rui_urban_major",
            "rui_urban_minor",
            "region_east_midlands",
            "region_eastern",
            "region_london",
            "region_north_east",
            "region_north_west",
            "region_south_east",
            "region_south_west",
            "region_west_midlands",
            "region_yorkshire_and_the_humber",
        ],
        "prediction_destination": "s3://sfc-mt-sagemaker-demo/predict/care_home_filled_posts_prediction",
    },
}
