repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.105.0"
    hooks:
      - id: terraform_fmt

  - repo: local
    hooks:
      - id: ban-show
        name: Block .show() usage
        entry: bash scripts/prevent_show_usage.sh
        language: system
        types: [python]

      - id: black
        name: black
        entry: uv run black
        language: system
        types: [python]

      - id: pydoclint
        name: pydoclint
        entry: uv run pydoclint --style=google --quiet
        language: system
        types: [python]

      - id: uv-lock
        name: uv-lock
        entry: uv lock --check
        language: system
        files: ^pyproject\.toml$
        pass_filenames: false
