from dataclasses import dataclass


@dataclass
class JobCalculationConstants:

    BEDS_IN_WORKPLACE_THRESHOLD: int = 0

    BEDS_TO_JOB_COUNT_INTERCEPT: float = 8.40975704621392
    BEDS_TO_JOB_COUNT_COEFFICIENT: float = 1.0010753137758377001
    MIN_ABS_DIFFERENCE_BETWEEN_TOTAL_STAFF_AND_WORKER_RECORD_COUNT: int = 5
    MIN_PERCENTAGE_DIFFERENCE_BETWEEN_TOTAL_STAFF_AND_WORKER_RECORD_COUNT: float = 0.1

    MIN_TOTAL_STAFF_VALUE_PERMITTED: int = 3
    MIN_WORKER_RECORD_COUNT_PERMITTED: int = 3
