PIR_BASE_PATH = "s3://sfc-data-engineering/domain=CQC/dataset=pir/"
ASCWDS_WORKPLACE_BASE_PATH = "s3://sfc-data-engineering/domain=ASCWDS/dataset=workplace"
ASCWDS_WORKER_BASE_PATH = "s3://sfc-data-engineering/domain=ASCWDS/dataset=worker"
CQC_LOCATIONS_BASE_PATH = "s3://sfc-data-engineering/domain=CQC/dataset=locations-api/"
CQC_PROVIDERS_BASE_PATH = "s3://sfc-data-engineering/domain=CQC/dataset=providers-api/"
