version: 2.1

parameters:
  run-check-dataset-equality:
    type: boolean
    default: false

jobs:
  build-check-equality:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker Image
          command: docker buildx build  --platform linux/amd64 -t latest  lambdas/check_dataset_equality
      - aws-cli/setup:
          region: "eu-west-2"
      - run:
          name: Push Docker Image
          command: |
            # Authenticate Docker to ECR
            docker login -u AWS -p $(aws ecr get-login-password --region eu-west-2) 344210435447.dkr.ecr.eu-west-2.amazonaws.com

            # Push the image
            docker tag latest 344210435447.dkr.ecr.eu-west-2.amazonaws.com/check-dataset-equality-repo:${CIRCLE_BRANCH}
            docker push 344210435447.dkr.ecr.eu-west-2.amazonaws.com/check-dataset-equality-repo:${CIRCLE_BRANCH}

workflows:
  build:
    jobs:
      - build-check-equality:
          when: << pipeline.parameters.run-check-dataset-equality >>