version: 2.1

setup: true

environment:
  AWS_REGION: eu-west-2

orbs:
  path-filtering: circleci/path-filtering@3.0.0

workflows:
  setup-pipeline:
    jobs:
      - path-filtering/filter:
          name: check-updated-files
          base-revision: main
          config-path: .circleci/continue-config.yml
          mapping: |
            .*/jobs/.*\.py run-pyspark-tests true
            .*/fargate/.*\.py run-polars-tests true
            .*polars.*\.py run-polars-tests true
