from dataclasses import dataclass


@dataclass
class ReconciliationColumns:
    parents_or_singles_and_subs: str = "parents_or_singles_and_subs"
    new_potential_subs: str = "new_potential_subs"
    old_potential_subs: str = "old_potential_subs"
    missing_or_incorrect_potential_subs: str = "missing_or_incorrect_potential_subs"
    subject: str = "Subject"
    nmds: str = "NMDS"
    name: str = "Name"
    description: str = "Description"
    requester_name: str = "Requester_Name"
    requester_name_2: str = "Requester_Name_2"
    sector: str = "Sector"
    status: str = "Status"
    technician: str = "Technician"
    sfc_region: str = "SfC_Region"
    manual_call_log: str = "Manual_Call_Log"
    mode: str = "Mode"
    priority: str = "Priority"
    category: str = "Category"
    sub_category: str = "Subcategory"
    is_requester_named: str = "Is_requester_named_user_on_account"
    security_question: str = "Correct_answer_to_security_questiom_received"
    website: str = "Website"
    item: str = "Item"
    phone: str = "Phone"
    workplace_id: str = "Workplace_Id"
