from dataclasses import dataclass


@dataclass
class CqcProviderApiColumns:
    address_line_one: str = "postalAddressLine1"
    companies_house_number: str = "companiesHouseNumber"
    constituency: str = "constituency"
    county: str = "postalAddressCounty"
    deregistration_date: str = "deregistrationDate"
    inspection_directorate: str = "inspectionDirectorate"
    latitude: str = "onspdLatitude"
    local_authority: str = "localAuthority"
    location_ids: str = "locationIds"
    longitude: str = "onspdLongitude"
    name: str = "name"
    organisation_type: str = "organisationType"
    ownership_type: str = "ownershipType"
    phone_number: str = "mainPhoneNumber"
    postcode: str = "postalCode"
    provider_id: str = "providerId"
    region: str = "region"
    registration_date: str = "registrationDate"
    registration_status: str = "registrationStatus"
    town_or_city: str = "postalAddressTownCity"
    type: str = "type"
    uprn: str = "uprn"


@dataclass
class NewCqcProviderApiColumns:
    alsoKnownAs: str = "alsoKnownAs"
    brandId: str = "brandId"
    brandName: str = "brandName"
    charityNumber: str = "charityNumber"
    companiesHouseNumber: str = "companiesHouseNumber"
    constituency: str = "constituency"
    contacts: str = "contacts"
    currentRatings: str = "currentRatings"
    deregistrationDate: str = "deregistrationDate"
    historicRatings: str = "historicRatings"
    inspectionAreas: str = "inspectionAreas"
    inspectionCategories: str = "inspectionCategories"
    inspectionDirectorate: str = "inspectionDirectorate"
    lastInspection: str = "lastInspection"
    lastReport: str = "lastReport"
    localAuthority: str = "localAuthority"
    locationIds: str = "locationIds"
    mainPhoneNumber: str = "mainPhoneNumber"
    name: str = "name"
    odsCode: str = "odsCode"
    onspdIcbCode: str = "onspdIcbCode"
    onspdIcbName: str = "onspdIcbName"
    onspdLatitude: str = "onspdLatitude"
    onspdLongitude: str = "onspdLongitude"
    organisationType: str = "organisationType"
    ownershipType: str = "ownershipType"
    postalAddressCounty: str = "postalAddressCounty"
    postalAddressLine1: str = "postalAddressLine1"
    postalAddressLine2: str = "postalAddressLine2"
    postalAddressTownCity: str = "postalAddressTownCity"
    postalCode: str = "postalCode"
    providerId: str = "providerId"
    region: str = "region"
    registrationDate: str = "registrationDate"
    registrationStatus: str = "registrationStatus"
    regulatedActivities: str = "regulatedActivities"
    relationships: str = "relationships"
    reports: str = "reports"
    type: str = "type"
    unpublishedReports: str = "unpublishedReports"
    uprn: str = "uprn"
    website: str = "website"
