from pyspark.sql.types import (
    StructField,
    StructType,
    StringType,
    IntegerType,
    FloatType,
    TimestampType,
)

WORKER_SCHEMA = StructType(
    fields=[
        StructField("period", StringType(), True),
        StructField("establishmentid", IntegerType(), True),
        StructField("tribalid", FloatType(), True),
        StructField("tribalid_worker", FloatType(), True),
        StructField("parentid", FloatType(), True),
        StructField("orgid", IntegerType(), True),
        StructField("nmdsid", StringType(), True),
        StructField("workerid", IntegerType(), True),
        StructField("wrkglbid", StringType(), True),
        StructField("wkplacestat", IntegerType(), True),
        StructField("createddate", TimestampType(), True),
        StructField("updateddate", TimestampType(), True),
        StructField("savedate", TimestampType(), True),
        StructField("cqcpermission", IntegerType(), True),
        StructField("lapermission", IntegerType(), True),
        StructField("regtype", IntegerType(), True),
        StructField("providerid", StringType(), True),
        StructField("locationid", StringType(), True),
        StructField("esttype", IntegerType(), True),
        StructField("regionid", IntegerType(), True),
        StructField("cssr", IntegerType(), True),
        StructField("lauthid", IntegerType(), True),
        StructField("mainstid", FloatType(), True),
        StructField("emplstat", IntegerType(), True),
        StructField("mainjrid", IntegerType(), True),
        StructField("strtdate", TimestampType(), True),
        StructField("age", IntegerType(), True),
        StructField("gender", IntegerType(), True),
        StructField("disabled", IntegerType(), True),
        StructField("ethnicity", IntegerType(), True),
        StructField("isbritish", IntegerType(), True),
        StructField("nationality", IntegerType(), True),
        StructField("britishcitizen", IntegerType(), True),
        StructField("borninuk", IntegerType(), True),
        StructField("countryofbirth", IntegerType(), True),
        StructField("yearofentry", IntegerType(), True),
        StructField("homeregionid", IntegerType(), True),
        StructField("homecssrid", IntegerType(), True),
        StructField("homelauthid", IntegerType(), True),
        StructField("distwrkk", FloatType(), True),
        StructField("scerec", IntegerType(), True),
        StructField("startsec", IntegerType(), True),
        StructField("startage", IntegerType(), True),
        StructField("dayssick", FloatType(), True),
        StructField("dayssick_changedate", TimestampType(), True),
        StructField("dayssick_savedate", TimestampType(), True),
        StructField("zerohours", IntegerType(), True),
        StructField("averagehours", FloatType(), True),
        StructField("conthrs", FloatType(), True),
        StructField("salaryint", IntegerType(), True),
        StructField("salary", FloatType(), True),
        StructField("hrlyrate", FloatType(), True),
        StructField("pay_changedate", TimestampType(), True),
        StructField("pay_savedate", TimestampType(), True),
        StructField("ccstatus", IntegerType(), True),
        StructField("apprentice", IntegerType(), True),
        StructField("scqheld", IntegerType(), True),
        StructField("levelscqheld", IntegerType(), True),
        StructField("nonscqheld", IntegerType(), True),
        StructField("levelnonscqheld", IntegerType(), True),
        StructField("listqualsachflag", IntegerType(), True),
        StructField("listhiqualev", IntegerType(), True),
        StructField("jd16registered", IntegerType(), True),
        StructField("amhp", IntegerType(), True),
        StructField("trainflag", IntegerType(), True),
        StructField("flujab2020", IntegerType(), True),
        StructField("derivedfrom_hasbulkuploaded", IntegerType(), True),
        StructField("previous_pay", FloatType(), True),
        StructField("previous_mainjrid", FloatType(), True),
        StructField("version", StringType(), True),
        StructField("year", IntegerType(), True),
        StructField("month", IntegerType(), True),
        StructField("day", IntegerType(), True),
        StructField("import_date", TimestampType(), True),
        StructField("jr01flag", IntegerType(), True),
        StructField("jr02flag", IntegerType(), True),
        StructField("jr03flag", IntegerType(), True),
        StructField("jr04flag", IntegerType(), True),
        StructField("jr05flag", IntegerType(), True),
        StructField("jr06flag", IntegerType(), True),
        StructField("jr07flag", IntegerType(), True),
        StructField("jr08flag", IntegerType(), True),
        StructField("jr09flag", IntegerType(), True),
        StructField("jr10flag", IntegerType(), True),
        StructField("jr11flag", IntegerType(), True),
        StructField("jr15flag", IntegerType(), True),
        StructField("jr16flag", IntegerType(), True),
        StructField("jr17flag", IntegerType(), True),
        StructField("jr22flag", IntegerType(), True),
        StructField("jr23flag", IntegerType(), True),
        StructField("jr24flag", IntegerType(), True),
        StructField("jr25flag", IntegerType(), True),
        StructField("jr26flag", IntegerType(), True),
        StructField("jr27flag", IntegerType(), True),
        StructField("jr34flag", IntegerType(), True),
        StructField("jr35flag", IntegerType(), True),
        StructField("jr36flag", IntegerType(), True),
        StructField("jr37flag", IntegerType(), True),
        StructField("jr38flag", IntegerType(), True),
        StructField("jr39flag", IntegerType(), True),
        StructField("jr40flag", IntegerType(), True),
        StructField("jr41flag", IntegerType(), True),
        StructField("jr42flag", IntegerType(), True),
        StructField("jr16cat1", IntegerType(), True),
        StructField("jr16cat2", IntegerType(), True),
        StructField("jr16cat3", IntegerType(), True),
        StructField("jr16cat4", IntegerType(), True),
        StructField("jr16cat5", IntegerType(), True),
        StructField("jr16cat6", IntegerType(), True),
        StructField("jr16cat7", IntegerType(), True),
        StructField("jr16cat8", IntegerType(), True),
    ]
)
