from projects._03_independent_cqc._04_model.utils.value_labels import (
    RegionLabels,
    RelatedLocationLabels,
    RuralUrbanLabels,
    ServicesLabels,
    SpecialismsLabels,
)
from utils.column_names.ind_cqc_pipeline_columns import IndCqcColumns as IndCQC

model_registry = {
    "care_home": {
        "version": "7.0.0",
        "auto_retrain": True,
        "model_type": "lasso",
        "model_params": {"alpha": 0.001},
        "dependent": IndCQC.imputed_filled_posts_per_bed_ratio_model,
        "features": [
            IndCQC.activity_count_capped,
            IndCQC.cqc_location_import_date_indexed,
            IndCQC.number_of_beds,
            IndCQC.banded_bed_ratio_rolling_average_model,
            IndCQC.service_count_capped,
            list(RegionLabels.labels_dict.keys()),
            list(RuralUrbanLabels.care_home_labels_dict.keys()),
            list(ServicesLabels.care_home_labels_dict.keys()),
            list(SpecialismsLabels.labels_dict.keys()),
        ],
    },
    "non_residential_without_dormancy": {
        "version": "5.0.0",
        "auto_retrain": True,
        "model_type": "lasso",
        "model_params": {"alpha": 0.001},
        "dependent": IndCQC.imputed_filled_post_model,
        "features": [
            IndCQC.activity_count_capped,
            IndCQC.cqc_location_import_date_indexed,
            IndCQC.posts_rolling_average_model,
            IndCQC.service_count_capped,
            IndCQC.time_registered_capped_at_four_years,
            list(RelatedLocationLabels.labels_dict.keys()),
            list(RegionLabels.labels_dict.keys()),
            list(RuralUrbanLabels.non_res_labels_dict.keys()),
            list(ServicesLabels.non_res_labels_dict.keys()),
            list(SpecialismsLabels.labels_dict.keys()),
        ],
    },
    "non_residential_with_dormancy": {
        "version": "6.0.0",
        "auto_retrain": True,
        "model_type": "lasso",
        "model_params": {"alpha": 0.001},
        "dependent": IndCQC.imputed_filled_post_model,
        "features": [
            IndCQC.activity_count_capped,
            IndCQC.cqc_location_import_date_indexed,
            IndCQC.cqc_location_import_date_indexed_squared,
            IndCQC.posts_rolling_average_model,
            IndCQC.service_count_capped,
            IndCQC.time_registered,
            IndCQC.time_since_dormant,
            list(RelatedLocationLabels.labels_dict.keys()),
            list(RegionLabels.labels_dict.keys()),
            list(RuralUrbanLabels.non_res_labels_dict.keys()),
            list(ServicesLabels.non_res_labels_dict.keys()),
            list(SpecialismsLabels.labels_dict.keys()),
        ],
    },
    "non_res_pir": {
        "version": "3.0.0",
        "auto_retrain": True,
        "model_type": "linear",
        "model_params": {"fit_intercept": False},
        "dependent": IndCQC.ascwds_filled_posts_dedup_clean,
        "features": [IndCQC.pir_people_directly_employed_dedup],
    },
}
