ascwds_known_care_home: str = "ASCWDS known care home"
ascwds_known_non_residential: str = "ASCWDS known non residential"
capacity_tracker_known_care_home: str = "capacity tracker known care home"
capacity_tracker_known_non_residential: str = "capacity tracker known non residential"
pir_known_care_home: str = "PIR known care home"
pir_known_non_residential: str = "PIR known non residential"
unknown: str = "unknown"

care_home_with_nursing: str = "Care home with nursing"
care_home_without_nursing: str = "Care home without nursing"
non_residential: str = "non-residential"
