CQC_ID: str = "CQC_ID"
NURSES_EMPLOYED: str = "Nurses_Employed"
CARE_WORKERS_EMPLOYED: str = "Care_Workers_Employed"
NON_CARE_WORKERS_EMPLOYED: str = "Non_Care_Workers_Employed"
AGENCY_NURSES_EMPLOYED: str = "Agency_Nurses_Employed"
AGENCY_CARE_WORKERS_EMPLOYED: str = "Agency_Care_Workers_Employed"
AGENCY_NON_CARE_WORKERS_EMPLOYED: str = "Agency_Non_Care_Workers_Employed"
CQC_CARE_WORKERS_EMPLOYED: str = "CQC_Care_Workers_Employed"
